version: '3.1'
services:
  frontend:
    build: ./frontend
    container_name: ${PROJ_NAME}_frontend
    command: bash -c "npm run --prefix ./frontend start"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
